# Generated by Django 4.2.1 on 2023-11-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0003_alter_post_date_alter_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='event_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='keyword',
            new_name='location',
        ),
    ]
