# Generated by Django 4.2.1 on 2023-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_likes',
            field=models.IntegerField(default=1),
        ),
    ]
